title: Stack Problems
description: My Personal Stack Problems
author: Tuan Bach Van
github: https://github.com/bachvtuan
about: I'm Full Stack Developer and Blockchain lover
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:

    - icon: fa-twitter
      link: "https://twitter.com/bvtuan"
    - icon: fa-github
      link: "https://github.com/bachvtuan"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://bachvtuan.github.io/"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
